// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FtuloTnQPRQXwfba1Pda3vCLMKzWmPA',
    appId: '1:920738963019:web:9378af849a78f72d75f7ce',
    messagingSenderId: '920738963019',
    projectId: 'to-do-list-fba20',
    authDomain: 'to-do-list-fba20.firebaseapp.com',
    storageBucket: 'to-do-list-fba20.appspot.com',
    measurementId: 'G-T7VSXJGDTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoCldd844jytBDD5VZxKzOnfjuwMM58s',
    appId: '1:920738963019:android:11562708618870b675f7ce',
    messagingSenderId: '920738963019',
    projectId: 'to-do-list-fba20',
    storageBucket: 'to-do-list-fba20.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4FtuloTnQPRQXwfba1Pda3vCLMKzWmPA',
    appId: '1:920738963019:web:dbb0589136a69cca75f7ce',
    messagingSenderId: '920738963019',
    projectId: 'to-do-list-fba20',
    authDomain: 'to-do-list-fba20.firebaseapp.com',
    storageBucket: 'to-do-list-fba20.appspot.com',
    measurementId: 'G-5M0M1Z6K3K',
  );
}
